# Generated by Django 3.2.6 on 2021-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('HS_marks', models.IntegerField()),
                ('current_cgpa', models.IntegerField()),
                ('current_backlogs', models.TextField()),
            ],
        ),
    ]
